## Numpy for random arrays

In [ ]:
# Generat an array of random float between 0 and 1 and elements number can be changed by making argument and for more
# dimensions use second and more argument
import numpy as np
a = np.random.rand(3, 3, 3)
print(a)

In [17]:
# first two argument for range and then others for dimensions and for higher dimensions use a tuple
a = np.random.randint(0, 10, (3,5))
print(a)

[[5 4 9 4 5]
 [9 9 9 1 3]
 [0 7 8 4 9]]


In [22]:
# shuffle arrays
arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print(arr)
np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [24]:
# seed for keeping track
np.random.seed(1)
print(np.random.rand(3, 3))
np.random.seed(1)
print(np.random.rand(3, 3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
